Import('env')

testa = env.compileAndJar('testa.jar', 'testa')
env.compileAndJar('example.jar', 'example', libs=[testa], standalone=True,
  main='example.main')
env.InstallAs('puretest.jar', 'example.jar')
